import { useEffect } from 'react';
import Footer from '../components/Footer';
import './PrivacyPage.css';

export default function PrivacyPage() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <>
      <div className="privacy-page">
        <div className="privacy-container">
          <h1>Privacy Policy / Datenschutzerklärung</h1>

          <div className="privacy-section">
            <h2>1. General Information</h2>
            <p>
              The protection of your personal data is very important to us. This privacy policy explains what data we collect, how we use it, and what rights you have regarding your data.
            </p>
            <p>
              The processing of personal data (such as name, email address, or IP address) is carried out in accordance with the General Data Protection Regulation (GDPR) and applicable national data protection laws.
            </p>
          </div>

          <div className="privacy-section">
            <h2>2. Controller</h2>
            <p>
              The controller responsible for data processing on this website is:
            </p>
            <p>
              Abhishek Arora<br />
              Bruchweg 52<br />
              32657 Lemgo<br />
              Germany
            </p>
            <p>
              <strong>Phone:</strong> <a href="tel:+491623919824">+49 162 3919824</a><br />
              <strong>Email:</strong> <a href="mailto:abhishekarora.de@gmail.com">abhishekarora.de@gmail.com</a>
            </p>
          </div>

          <div className="privacy-section">
            <h2>3. Hosting</h2>
            <p>
              This website is hosted by Bolt Hosting. The hosting provider processes personal data necessary to provide the website.
            </p>
            <p>This includes in particular:</p>
            <ul>
              <li>IP addresses</li>
              <li>connection data</li>
              <li>server requests</li>
            </ul>
            <p>
              The processing is carried out to ensure the secure and stable operation of the website.
            </p>
            <p>
              <strong>Legal basis:</strong> Art. 6(1)(f) GDPR (legitimate interest in secure website operation).
            </p>
          </div>

          <div className="privacy-section">
            <h2>4. Server Log Files</h2>
            <p>
              The hosting provider automatically collects and stores information in so-called server log files, which your browser automatically transmits to us.
            </p>
            <p>These may include:</p>
            <ul>
              <li>IP address</li>
              <li>browser type and version</li>
              <li>operating system used</li>
              <li>referrer URL</li>
              <li>hostname of the accessing computer</li>
              <li>time of the server request</li>
            </ul>
            <p>
              This data is not combined with other data sources.
            </p>
            <p>
              The collection of this data is necessary to ensure the technical stability, security, and proper functioning of the website.
            </p>
            <p>
              <strong>Legal basis:</strong> Art. 6(1)(f) GDPR.
            </p>
          </div>

          <div className="privacy-section">
            <h2>5. Google Analytics</h2>
            <p>
              This website uses Google Analytics, a web analytics service provided by Google LLC.
            </p>
            <p>
              Google Analytics uses cookies and similar technologies to analyze how users interact with the website.
            </p>
            <p>The following information may be collected:</p>
            <ul>
              <li>pages visited</li>
              <li>time spent on pages</li>
              <li>device information</li>
              <li>approximate geographic location</li>
              <li>IP address (anonymized where possible)</li>
            </ul>
            <p>
              This information is used to evaluate website usage and improve our services.
            </p>
            <p>
              Data may be transferred to servers in the United States.
            </p>
            <p>
              <strong>Legal basis:</strong> Art. 6(1)(a) GDPR (consent) where applicable.
            </p>
            <p>
              Users can prevent the collection of data generated by Google Analytics by adjusting their browser settings or by declining analytics cookies where a consent banner is provided.
            </p>
          </div>

          <div className="privacy-section">
            <h2>6. Contact via Email or Contact Form</h2>
            <p>
              If you contact us via email or through the contact form on our website, the information you provide will be stored for the purpose of processing your request.
            </p>
            <p>This may include:</p>
            <ul>
              <li>name</li>
              <li>email address</li>
              <li>message content</li>
            </ul>
            <p>
              The data will not be shared with third parties without your consent.
            </p>
            <p>
              <strong>Legal basis:</strong> Art. 6(1)(b) GDPR (processing necessary for communication or pre-contractual measures).
            </p>
          </div>

          <div className="privacy-section">
            <h2>7. Newsletter and Waitlist</h2>
            <p>
              Users may subscribe to a newsletter or product waitlist on our website.
            </p>
            <p>For this purpose we collect:</p>
            <ul>
              <li>email address</li>
              <li>optional additional information provided by the user</li>
            </ul>
            <p>
              The data will only be used to send updates regarding the project, product launches, or related information.
            </p>
            <p>
              Users can unsubscribe at any time via the unsubscribe link included in emails.
            </p>
            <p>
              <strong>Legal basis:</strong> Art. 6(1)(a) GDPR (consent).
            </p>
          </div>

          <div className="privacy-section">
            <h2>8. Investor Contact</h2>
            <p>
              The website may provide forms through which potential investors can contact us.
            </p>
            <p>Data submitted via these forms may include:</p>
            <ul>
              <li>name</li>
              <li>email address</li>
              <li>organization</li>
              <li>message or inquiry</li>
            </ul>
            <p>
              This information is used solely for communication regarding investment opportunities or fundraising.
            </p>
            <p>
              <strong>Legal basis:</strong> Art. 6(1)(b) GDPR or Art. 6(1)(f) GDPR.
            </p>
          </div>

          <div className="privacy-section">
            <h2>9. External Links</h2>
            <p>
              Our website may contain links to external platforms such as LinkedIn.
            </p>
            <p>
              If you click such a link, you will be redirected to the external provider. We have no control over the processing of personal data by these providers.
            </p>
            <p>
              Please refer to the privacy policies of the respective platforms.
            </p>
          </div>

          <div className="privacy-section">
            <h2>10. Data Retention</h2>
            <p>
              Personal data will only be stored for as long as necessary to fulfill the purposes described in this policy or as required by law.
            </p>
          </div>

          <div className="privacy-section">
            <h2>11. Your Rights Under GDPR</h2>
            <p>You have the following rights regarding your personal data:</p>
            <ul>
              <li>Right of access (Art. 15 GDPR)</li>
              <li>Right to rectification (Art. 16 GDPR)</li>
              <li>Right to erasure (Art. 17 GDPR)</li>
              <li>Right to restriction of processing (Art. 18 GDPR)</li>
              <li>Right to data portability (Art. 20 GDPR)</li>
              <li>Right to object to processing (Art. 21 GDPR)</li>
            </ul>
            <p>
              You also have the right to lodge a complaint with a supervisory authority.
            </p>
          </div>

          <div className="privacy-section">
            <h2>12. Changes to This Privacy Policy</h2>
            <p>
              We reserve the right to update this privacy policy to reflect changes in legal requirements or our services.
            </p>
            <p>
              The current version can always be found on this website.
            </p>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}
